FEBiblioteca/Controllers/HabitacionesController.cs
using FEBiblioteca.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FEBiblioteca.Controllers
{
    public class HabitacionesController : Controller
    {
        public async Task<IActionResult> Index()
        {
            GestorConexiones objconexion = new GestorConexiones();
            List<HabitacionesModel> lstresultados = await objconexion.ListarHabitaciones();
            return View(lstresultados);
        }

        public IActionResult AperturaCrearUsuario()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GuardarHabitaciones(HabitacionesModel P_Habitaciones)
        {

            ErrorViewModel msj = new ErrorViewModel();
            GestorConexiones objconexion = new GestorConexiones();
            List<HabitacionesModel> lstresultados = await objconexion.ConsultarHabitacion(new HabitacionesModel { Id_habitacion = P_Habitaciones.Id_habitacion });
            lstresultados.FirstOrDefault();
            if (lstresultados.Count == 0)
            {
                ReportesModel aux = new ReportesModel();
                aux.Reporte = "Se agregó la habitación " + P_Habitaciones.Id_habitacion + " con fecha " + DateTime.Now;
                await objconexion.AgregarHabitaciones(P_Habitaciones);
                await objconexion.AgregarReporte(aux);
                return RedirectToAction("Index");
            }
            else
            {
                msj.RequestId = "El usuario tiene una reserva por lo que no se puede eliminar";
                return RedirectToAction("Index");
            }
           
           
        }
      
        public async Task<IActionResult> EliminarHabitacion(int pHabitacion)
        {
            ReportesModel aux = new ReportesModel();
            aux.Reporte = "Se eliminó la habitación " + pHabitacion + " con fecha " + DateTime.Now;
            GestorConexiones objconexion = new GestorConexiones();
            await objconexion.EliminarHabitacion(new HabitacionesModel { Id_habitacion = pHabitacion });
            await objconexion.AgregarReporte(aux);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> VerInfoModificar(int pHabitacion)
        {
            GestorConexiones objconexion = new GestorConexiones();
            List<HabitacionesModel> lstresultados = await objconexion.ConsultarHabitacion(new HabitacionesModel { Id_habitacion = pHabitacion });
            return View(lstresultados.FirstOrDefault());
        }
        public async Task<IActionResult> ModificarHabitacion(HabitacionesModel P_Habitacion)
        {
            ReportesModel aux = new ReportesModel();
            aux.Reporte = "Se modificó la habitación " + P_Habitacion.Id_habitacion + " con fecha " + DateTime.Now;
            GestorConexiones objconexion = new GestorConexiones();
            await objconexion.ModificarHabitacion(P_Habitacion);
            await objconexion.AgregarReporte(aux);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> ConsultarHabitacionOcupada(HabitacionesModel P_Habitaciones)
        {
                 bool estaOcupado = P_Habitaciones.Ocupado;
                 GestorConexiones objconexion = new GestorConexiones();

                 List<HabitacionesModel> lstresultados = await objconexion.ConsultarHabitacionOcupada(P_Habitaciones);
                 return View(lstresultados);


        }

    }
}

FEBiblioteca/Controllers/UsuariosController.cs
using FEBiblioteca.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FEBiblioteca.Controllers
{
    public class UsuariosController : Controller
    {

        public async Task<IActionResult> Index()
        {
            GestorConexiones objconexion = new GestorConexiones();
            List<UsuariosModel> lstresultados = await objconexion.ListarUsuarios();
            return View(lstresultados);
        }


        public IActionResult CrearUsuario()
        {
            return View();
        }

   
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Registro()
        {
            return View();
        }

        public IActionResult Menu()
        {
            return View();
        }

        public IActionResult MenuAdministrador()
        {
            return View();
        }
 


        public async Task<IActionResult> InicioSesion(UsuariosModel P_Usuarios)
        {
            ErrorViewModel msj = new ErrorViewModel();
            GestorConexiones objconexion = new GestorConexiones();
            List<UsuariosModel> lstresultados = await objconexion.ConsultarInicioSesion(P_Usuarios);
            lstresultados.FirstOrDefault();
                
            if(lstresultados.Count == 0 )
            {
                msj.RequestId = "Usuario o contrasena no encontrados";
                return RedirectToAction("Login");
            }
            else
            {
                foreach (UsuariosModel usuario in lstresultados)
                {
                    //Arreglar la lista de opciones de cada perfil
                    // crear vista para perfil 2
                    if (usuario.Id_perfil == 2)
                    {
                            return RedirectToAction("Menu");
                    }
                    
                }
                // Crear vista para perfil 1
                return RedirectToAction("MenuAdministrador");
            }
        }

        ///Numero 1 = perfil administrador
        ///Numero 2 =  perfil usuario
        public async Task<IActionResult> Agregar(UsuariosModel P_Usuario)
        {
 
            ErrorViewModel msj = new ErrorViewModel();
            GestorConexiones objconexion = new GestorConexiones();
            List<UsuariosModel> lstresultados = await objconexion.ConsultarUsuarios(new UsuariosModel { Id_Usuario = P_Usuario.Id_Usuario });
            lstresultados.FirstOrDefault();
            if (lstresultados.Count == 0)
            {
                ReportesModel aux = new ReportesModel();
                aux.Reporte = "Se agregó el usuario " + P_Usuario.Id_Usuario + " con fecha " + DateTime.Now;
                await objconexion.Agregar(P_Usuario);
                await objconexion.AgregarReporte(aux);
                return RedirectToAction("Index");
            }
            else
            {
                msj.RequestId = "El usuario tiene una reserva por lo que no se puede eliminar";
                return RedirectToAction("Index");
            }
        }
        public async Task<IActionResult> Registrarse(UsuariosModel P_Usuario)
        {
            ErrorViewModel msj = new ErrorViewModel();
            GestorConexiones objconexion = new GestorConexiones();
            List<UsuariosModel> lstresultados = await objconexion.ConsultarUsuarios(new UsuariosModel { Id_Usuario = P_Usuario.Id_Usuario });
            lstresultados.FirstOrDefault();
            if (lstresultados.Count == 0)
            {
                ReportesModel aux = new ReportesModel();
                aux.Reporte = "Se registró el usuario " + P_Usuario.Id_Usuario + " con fecha " + DateTime.Now;
                P_Usuario.Id_perfil = 2;
                await objconexion.Agregar(P_Usuario);
                await objconexion.AgregarReporte(aux);
                return RedirectToAction("Login");
            }
            else
            {
                msj.RequestId = "El usuario tiene una reserva por lo que no se puede eliminar";
                return RedirectToAction("Registro");
            }
        }
        public async Task<IActionResult> EliminarUsuario(int pUsuario)
        {
            ErrorViewModel msj = new ErrorViewModel();
            GestorConexiones objconexion = new GestorConexiones();
            List<ReservaModel> lstresultados = await objconexion.ConsultarReservaPorIdUsuario(new ReservaModel { Id_usuario = pUsuario });
            lstresultados.FirstOrDefault();
            if (lstresultados.Count == 0)
            {
                ReportesModel aux = new ReportesModel();
                aux.Reporte = "Se eliminó el usuario " + pUsuario + " con fecha " + DateTime.Now;
                await objconexion.EliminarUsuario(new UsuariosModel { Id_Usuario = pUsuario });
                await objconexion.AgregarReporte(aux);
                return RedirectToAction("Index");
            }
            else
            {
                msj.RequestId = "El usuario tiene una reserva por lo que no se puede eliminar";
                return RedirectToAction("Index");
            }
        }


        public async Task<IActionResult> VerInfoModificar(int pUsuario)
        {
            GestorConexiones objconexion = new GestorConexiones();
            List<UsuariosModel> lstresultados = await objconexion.ConsultarUsuarios(new UsuariosModel { Id_Usuario = pUsuario });
            return View(lstresultados.FirstOrDefault());
        }
 

        public async Task<IActionResult> ModificarUsuario(UsuariosModel P_Usuario)
        {
            ReportesModel aux = new ReportesModel();
            aux.Reporte = "Se modificó el usuario " + P_Usuario.Id_Usuario + " con fecha " + DateTime.Now;
            GestorConexiones objconexion = new GestorConexiones();
            await objconexion.ModificarUsuario(P_Usuario);
            await objconexion.AgregarReporte(aux);
            return RedirectToAction("Index");
        }


    }
}

FEBiblioteca/Views/Habitaciones/AperturaCrearUsuario.cshtml
@model FEBiblioteca.Models.HabitacionesModel

@section noheader
{
    <h1></h1>
}

@{
    ViewData["Title"] = "AperturaCrearUsuario";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inicio Hotel</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <style>
        body {
            background-color: #f8f9fa;
            font-family: Arial, sans-serif;
            line-height: 1.6;
        }

        h1 {
            font-family: 'Times New Roman', Times, serif;
            color: #fff;
            font-size: 2.5rem;
            margin-top: 30px;
        }

        hr {
            border: 1px solid #007bff;
            margin: 20px 0;
            color: #fff;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #2c3e50; /* Fondo blanco para el contenido */
            border-radius: 5px; /* Añado bordes redondeados */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Agrego sombra al contenedor */
        }

        label {
            font-family: 'Times New Roman', Times, serif;
            color: #fff;
            font-weight: bold;
            font-size: 1.0rem;
        }

        .form-control {
            border-radius: 5px;
            border: 1px solid #ced4da;
        }

        .btn-primary {
            color: #fff;
            background-color: lightslategrey;
            border-color: #007bff;
        }

            .btn-primary:hover {
                background-color: #0056b3;
                border-color: #0056b3;
            }

        .btn-warning {
            background-color: #ffc107;
            border-color: #ffc107;
        }

            .btn-warning:hover {
                background-color: #e0a800;
                border-color: #e0a800;
            }

        .text-danger {
            color: #dc3545;
        }

        .btn-volver {
            color: #fff;
            background: lightslategrey;
        }
    </style>
</head>
<body>

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h1>
                    <img src="https://cdn-icons-png.flaticon.com/128/1069/1069454.png" alt="Logo" width="50" />
                    Crear Habitacion
                </h1>
                <hr />

                <form asp-action="GuardarHabitaciones" asp-controller="Habitaciones" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Id_habitacion" class="control-label">ID Habitación</label>
                        <input asp-for="Id_habitacion" class="form-control" />
                        <span asp-validation-for="Id_habitacion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Numero_habitacion" class="control-label">Número de Habitación</label>
                        <input asp-for="Numero_habitacion" class="form-control" />
                        <span asp-validation-for="Numero_habitacion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Tipo_habitacion" class="control-label">Tipo de Habitación</label>
                        <input asp-for="Tipo_habitacion" class="form-control" />
                        <span asp-validation-for="Tipo_habitacion" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Precio" class="control-label"></label>
                        <input asp-for="Precio" class="form-control" />
                        <span asp-validation-for="Precio" class="text-danger"></span>
                    </div>
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Ocupado" /> @Html.DisplayNameFor(model => model.Ocupado)
                        </label>
                    </div>
                    <div class="form-group">

                        <input type="submit" value="Guardar" class="btn btn-primary" />
                    </div>
                </form>

                <div class="mt-3 text-center">

                    <a class="btn btn-primary btn-lg" asp-action="Index" asp-controller="Habitaciones">Regresar a habitaciones</a>
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FEBiblioteca/Views/Habitaciones/ConsultarHabitacionOcupada.cshtml
@model IEnumerable<FEBiblioteca.Models.HabitacionesModel>

@{
    ViewData["Title"] = "ConsultarHabitacionOcupada";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <style>
        /* Agrega estilos CSS aquí según tus necesidades */
        body {
            font-family: Arial, sans-serif;
            background-color: #2c3e50; /* Update background color */
            color: #ecf0f1; /* Text color */
        }

        h1, h2 {
            text-align: center;
            color: #ecf0f1; /* Text color */
        }

        form {
            margin-bottom: 20px;
        }

        table {
            width: 80%;
            margin: 20px auto;
            border-collapse: collapse;
            background-color: white;
            color: #2c3e50; /* Text color */
        }

        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
        }

        .btn-crear {
            display: inline-block;
            padding: 10px 20px;
            font-size: 16px;
            text-align: center;
            text-decoration: none;
            background-color: #4caf50;
            color: white;
            border-radius: 5px;
        }
    </style>

</head>
<body>

    <h1>Consultar Habitacion Ocupada</h1>

    <center>
        <h2>Seleccione si desea ver las habitaciones disponibles</h2>
        <hr />
        @foreach (var item in Model)
        {
            bool estaOcupado = item.Ocupado;
            <form action="ConsultarHabitacionOcupada" method="post">
                <!-- ... Otros campos del formulario ... -->
                <input id="Radio1" type="radio" name="Ocupado" value="true" /> Ocupado
                <input id="Radio2" type="radio" name="Ocupado" value="" /> No Ocupado
                <!-- ... Otros campos del formulario ... -->
                <button type="submit">Seleccionar</button>
            </form>
        }
    </center>

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id_habitacion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Numero_habitacion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Tipo_habitacion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Precio)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ocupado)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id_habitacion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Numero_habitacion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Tipo_habitacion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Precio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ocupado)
                    </td>
                    <td>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <p>
        <a class="btn btn-crear" asp-action="Index" asp-controller="Habitaciones">Regresar al Inicio</a>
    </p>

    @section Scripts{
        <script>
            // Capturamos el elemento radio por su id
            const radioElement = document.getElementById('Radio1');

            // Agregamos un evento 'change' para detectar cuando el radio button cambia de estado
            radioElement.addEventListener('change', function () {
                // Verificamos si el radio button está marcado o no
                const estaOcupado = radioElement.checked;

                // Hacemos algo con el valor capturado, por ejemplo, mostrarlo en la consola
                console.log('El radio button está marcado:', estaOcupado);
            });
        </script>
    }
</body>
</html>

FEBiblioteca/Views/Habitaciones/EliminarHabitacion.cshtml
@model FEBiblioteca.Models.HabitacionesModel

@{
    ViewData["Title"] = "EliminarHabitacion";
}

<h1><img src="https://cdn-icons-png.flaticon.com/512/2306/2306341.png" alt="Logo" width="50" />
    Eliminar Habitación</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Habitaciones</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id_habitacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id_habitacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Numero_habitacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Numero_habitacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo_habitacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo_habitacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ocupado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ocupado)
        </dd>
    </dl>
    
    <form asp-action="EliminarHabitacion">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-warning" asp-action="Index" asp-controller="Habitaciones">Regresar a habitaciones</a>
    </form>
</div>

FEBiblioteca/Views/Habitaciones/Index.cshtml
@model IEnumerable<FEBiblioteca.Models.HabitacionesModel>
@section noheader
{
    <h1></h1>
}


@{
    ViewData["Title"] = "Index";
}



    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Habitaciones Registradas - Hotel</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            background-color: #f8f9fa;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #203869;
            padding: 10px;
            text-align: center;
            color: #fff;
            margin-bottom: 20px;
        }

            header img {
                vertical-align: middle;
                margin-right: 10px;
            }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #2c3e50; /* Fondo blanco para el contenido */
            border-radius: 5px; /* Añado bordes redondeados */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Agrego sombra al contenedor */
        }

        .btn {
            display: inline-block;
            padding: 10px 20px;
            color: #fff;
            text-decoration: none;
            border: none;
            border-radius: 5px;
            margin-right: 10px;
            transition: background-color 0.3s ease;
            cursor: pointer;
        }

        /* Estilo para el botón de Crear */
        .btn-crear {
            background-color: #28a745;
        }

        .btn-volver {
            background: lightslategrey;
        }
        /* Estilo para el botón de Editar */
        .btn-editar {
            background-color: skyblue;
        }

        /* Estilo para el botón de Eliminar */
        .btn-eliminar {
            background-color: #9b0b0b;
        }

        /* Estilo al pasar el cursor sobre los botones */
        .btn:hover {
            opacity: 0.8;
        }

        .table {
            width: 100%;
            border-collapse: collapse;
            font-family: 'Times New Roman', Times, serif; /* Tipo de letra Times New Roman */
            background-color: whitesmoke; /* Fondo gris más claro */
            color: #333333; /* Color de texto gris oscuro */
            padding: 10px; /* Añade espacio interno */
            text-align: center; /* Centra el texto */
            border-bottom: 2px solid #aaaaaa; /* Añade una línea inferior */
        }

            .table th, .table td {
                padding: 10px;
                border-bottom: 1px solid #ddd;
            }

            .table th {
                background-color: #f2f2f2;
                text-align: left;
            }

            .table td {
                text-align: center;
            }


        body {
            font-family: 'Times New Roman', Times, serif;
        }

        .container2 {
            width: 50%; /* Ancho del contenedor */
            margin: 0 auto; /* Centrar horizontalmente */
            padding: 20px;
            border: solid;
            border-color: black;
            border-radius: 15px;
        }

        .container label {
            display: block; /* Mostrar cada etiqueta en una línea nueva */
            text-align: center; /* Centrar etiquetas */
            color: #fff;
            margin-bottom: 10px; /* Espacio entre etiquetas */
            font-size: 18px; /* Espacio entre etiquetas */
        }

        .container input[type="search"],
        .container input[type="text"] {
            width: calc(100% - 12px); /* Ancho del input menos el ancho del borde */
            padding: 6px; /* Espaciado interno */
            color: rgba(0, 0, 0, 0.1); /* color de letra del texto */
            margin-top: 5px; /* Espacio entre inputs */
            box-sizing: border-box; /* Incluir padding en el ancho total */
            font-size: 16px
        }

        .container button {
            width: 100%; /* Ancho completo del botón */
            padding: 8px;
            margin-top: 10px; /* Espacio entre botón y inputs */
            border-radius: 15px;
            box-sizing: border-box; /* Incluir padding en el ancho total */
        }

            /* Estilos adicionales para el botón de tipo 'submit' */
            .container button[type="submit"] {
                background-color: #007bff; /* Color de fondo */
                color: white; /* Color del texto */
                border: none; /* Quitar borde */
                cursor: pointer; /* Cambiar cursor al pasar por encima */
            }
    </style>
</head>
<body>
    <header>
        <h1>
            <img src="https://cdn-icons-png.flaticon.com/128/1069/1069454.png" alt="Logo" width="50" />
            Lista de Habitaciones Registrados
        </h1>
    </header>

    

    <div class="container">


        <table class="table">
            <thead>
                <tr>
                    <th>ID Habitación</th>
                    <th>Tipo de Habitación</th>
                    <th>Número de Habitación</th>
                    <th>Precio</th>
                    <th>Ocupado</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id_habitacion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Tipo_habitacion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Numero_habitacion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Precio)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Ocupado)
                        </td>
                        <td>
                            @Html.ActionLink("Crear", "AperturaCrearUsuario", new { pHabitacion = item.Id_habitacion }, new { @class = "btn btn-crear" })|
                            @Html.ActionLink("Editar", "VerInfoModificar", new { pHabitacion = item.Id_habitacion }, new { @class = "btn btn-editar" }) |
                            @Html.ActionLink("Eliminar", "EliminarHabitacion", new { pHabitacion = item.Id_habitacion }, new { @class = "btn btn-eliminar" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <p>
            <a class="btn btn-crear" asp-action="MenuAdministrador" asp-controller="Usuarios">Regresar a Inicio</a>\
            <a class="btn btn-crear" asp-action="ConsultarHabitacionOcupada" asp-controller="Habitaciones">Habitaciones disponibles</a>
        </p>
    </div>
</body>
</html>