FEBiblioteca/Controllers/PagosController.cs
using FEBiblioteca.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FEBiblioteca.Controllers
{
    public class PagosController : Controller
    {

        public async Task<IActionResult> Index()
        {
            GestorConexiones objconexion = new GestorConexiones();
            List<PagosModel> lstresultados = await objconexion.ListarPagos();
            return View(lstresultados);
        }

        public IActionResult CrearPago()
        {
            return View();
        }


        public async Task<IActionResult> EliminarPagos(int pPagos)
        {
            ReportesModel aux = new ReportesModel();
            aux.Reporte = "Se eliminó el pago " + pPagos + " con fecha " + DateTime.Now;
            GestorConexiones objconexion = new GestorConexiones();
            await objconexion.EliminarPagos(new PagosModel { Id_pago = pPagos });
            await objconexion.AgregarReporte(aux);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> VerInfoModificar(int pPago)
        {
            GestorConexiones objconexion = new GestorConexiones();
            List<PagosModel> lstresultados = await objconexion.ConsultarPago(new PagosModel { Id_pago = pPago });
            return View(lstresultados.FirstOrDefault());
        }


        public IActionResult Ventas()
        {
            return View();
        }

        public async Task<IActionResult> VerMontoTotal(PagosModel P_Pago)
        {
           
            GestorConexiones objconexion = new GestorConexiones();

            // Llama al método ConsultarTotalGenerado para obtener el total generado en el rango de fechas
            List<PagosModel> lstresultados = await objconexion.ConsultarMontoTotal(P_Pago);

            foreach (PagosModel pago in lstresultados)
            {
                decimal totalGenerado;
                totalGenerado = pago.Total;
                ViewData["TotalGenerado"] = totalGenerado;
                // Aquí puedes hacer lo que necesites con el totalGenerado, por ejemplo, pasarlo a la vista o usarlo en otra parte del código
                // En este ejemplo, lo estamos almacenando en ViewData para pasarlo a la vista
            }



            return View(lstresultados);
        }
        public async Task<IActionResult> ModificarPagos(PagosModel P_Pagos)
        {
            ReportesModel aux = new ReportesModel();
            aux.Reporte = "Se modificó el pago " + P_Pagos.Id_pago + " con fecha " + DateTime.Now;
            GestorConexiones objconexion = new GestorConexiones();
            await objconexion.ModificarPagos(P_Pagos);
            await objconexion.AgregarReporte(aux);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> GuardarPago(PagosModel P_Pagos)
        {

            ErrorViewModel msj = new ErrorViewModel();
            GestorConexiones objconexion = new GestorConexiones();
            List<PagosModel> lstresultados = await objconexion.ConsultarPago(new PagosModel { Id_pago = P_Pagos.Id_pago });
            lstresultados.FirstOrDefault();
            if (lstresultados.Count == 0)
            {
                ReportesModel aux = new ReportesModel();
                aux.Reporte = "Se agregó el pago " + P_Pagos.Id_pago + " con fecha " + DateTime.Now;
                await objconexion.AgregarPagos(P_Pagos);
                await objconexion.AgregarReporte(aux);
                return RedirectToAction("Index");
            }
            else
            {
                msj.RequestId = "El usuario tiene una reserva por lo que no se puede eliminar";
                return RedirectToAction("Index");
            }
        }

       
      
    }
}

FEBiblioteca/Controllers/ReportesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FEBiblioteca.Models;

namespace FEBiblioteca.Controllers
{
    public class ReportesController : Controller
    {
        public async Task<IActionResult> Index()
        {
            GestorConexiones objconexion = new GestorConexiones();
            List<ReportesModel> lstresultados = await objconexion.ListaReportes();
            return View(lstresultados);
        }

        public IActionResult AperturaCrearReporte()
        {
            return View();
        }

        public async Task<IActionResult> VerInfoModificar(string pReporte)
        {
            GestorConexiones objconexion = new GestorConexiones();
            ReportesModel entidad = await objconexion.ConsultarReportePorID(new ReportesModel { id_reporte = pReporte });
            return View(entidad);
        }

        [HttpPost]
        public async Task<IActionResult> GuardarReporte(ReportesModel P_Reporte)
        {
            GestorConexiones objconexion = new GestorConexiones();
            await objconexion.AgregarReporte(P_Reporte);
            return RedirectToAction("Index");
        }
      
    }
}

FEBiblioteca/Controllers/ReservaController.cs
using FEBiblioteca.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FEBiblioteca.Controllers
{
    public class ReservaController : Controller
    {

        public async Task<IActionResult> Index(int BuscarUsuario, int BuscarCodigo)
        {
            GestorConexiones objconexion = new GestorConexiones();
            List<ReservaModel> resultado = await objconexion.ListarReserva();

            //Aqui se aplica filtrado sobre la lista a mostrar
            if (BuscarUsuario >0)
                resultado = resultado.Where(item => item.Id_usuario.Equals(BuscarUsuario)).ToList();
            else if(BuscarCodigo>0)
                resultado = resultado.Where(item => item.Id_reserva.Equals(BuscarCodigo)).ToList();

            return View(resultado);
        }

        public async Task<IActionResult> Indexa(int BuscarUsuario, int BuscarCodigo)
        {
            GestorConexiones objconexion = new GestorConexiones();
            List<ReservaModel> resultado = await objconexion.ListarReserva();

            //Aqui se aplica filtrado sobre la lista a mostrar
            if (BuscarUsuario > 0)
                resultado = resultado.Where(item => item.Id_usuario.Equals(BuscarUsuario)).ToList();
            else if (BuscarCodigo > 0)
                resultado = resultado.Where(item => item.Id_reserva.Equals(BuscarCodigo)).ToList();

            return View(resultado);
        }

        public IActionResult CrearReservaa()
         {
             return View();
         }

        public IActionResult CrearReserva()
        {
            return View();
        }

        public async Task<IActionResult> GuardarReserva(ReservaModel P_Reservas)
        {
            ErrorViewModel msj = new ErrorViewModel();
            GestorConexiones objconexion = new GestorConexiones();
            List<ReservaModel> lstresultados = await objconexion.ConsultarReserva(new ReservaModel { Id_reserva = P_Reservas.Id_reserva });
            lstresultados.FirstOrDefault();
            if (lstresultados.Count == 0)
            {
                ReportesModel aux = new ReportesModel();
                aux.Reporte = "Se agregó la reserva "+ P_Reservas.Id_reserva+ " con fecha "+DateTime.Now;
                await objconexion.AgregarReservas(P_Reservas);
                await objconexion.AgregarReporte(aux);
                return RedirectToAction("Index");
            }
            else
            {
                msj.RequestId = "El usuario tiene una reserva por lo que no se puede eliminar";
                return RedirectToAction("Index");
            }
          
           
        }
        public async Task<IActionResult> GuardarReservaa(ReservaModel P_Reservas)
        {
            ErrorViewModel msj = new ErrorViewModel();
            GestorConexiones objconexion = new GestorConexiones();
            List<ReservaModel> lstresultados = await objconexion.ConsultarReserva(new ReservaModel { Id_reserva = P_Reservas.Id_reserva });
            lstresultados.FirstOrDefault();
            if (lstresultados.Count == 0)
            {
                ReportesModel aux = new ReportesModel();
                aux.Reporte = "Se agregó la reserva " + P_Reservas.Id_reserva + " con fecha " + DateTime.Now;
                await objconexion.AgregarReservas(P_Reservas);
                await objconexion.AgregarReporte(aux);
                return RedirectToAction("Indexa");
            }
            else
            {
                msj.RequestId = "El usuario tiene una reserva por lo que no se puede eliminar";
                return RedirectToAction("Indexa");
            }


        }

        public async Task<IActionResult> EliminarReserva(int pReserva)
        {
            ReportesModel aux = new ReportesModel();
            aux.Reporte = "Se eliminó la reserva " + pReserva + " con fecha " + DateTime.Now;
            GestorConexiones objconexion = new GestorConexiones();
            await objconexion.EliminarReserva(new ReservaModel { Id_reserva = pReserva });
            await objconexion.AgregarReporte(aux);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> EliminarReservaa(int pReserva)
        {
            ReportesModel aux = new ReportesModel();
            aux.Reporte = "Se eliminó la reserva " + pReserva + " con fecha " + DateTime.Now;
            GestorConexiones objconexion = new GestorConexiones();
            await objconexion.EliminarReserva(new ReservaModel { Id_reserva = pReserva });
            await objconexion.AgregarReporte(aux);
            return RedirectToAction("Indexa");
        }
        public async Task<IActionResult> VerInfoModificar(int pReserva)
        {
            GestorConexiones objconexion = new GestorConexiones();
            List<ReservaModel> lstresultados = await objconexion.ConsultarReserva(new ReservaModel { Id_reserva = pReserva });
            return View(lstresultados.FirstOrDefault());
        }

        public async Task<IActionResult> VerInfoModificara(int pReserva)
        {
            GestorConexiones objconexion = new GestorConexiones();
            List<ReservaModel> lstresultados = await objconexion.ConsultarReserva(new ReservaModel { Id_reserva = pReserva });
            return View(lstresultados.FirstOrDefault());
        }

        public async Task<IActionResult> ModificarReserva(ReservaModel P_Reserva)
        {
            ReportesModel aux = new ReportesModel();
            aux.Reporte = "Se modificó la reserva " + P_Reserva.Id_reserva + " con fecha " + DateTime.Now;
            GestorConexiones objconexion = new GestorConexiones();
            await objconexion.ModificarReserva(P_Reserva);
            await objconexion.AgregarReporte(aux);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ModificarReservaa(ReservaModel P_Reserva)
        {
            ReportesModel aux = new ReportesModel();
            aux.Reporte = "Se modificó la reserva " + P_Reserva.Id_reserva + " con fecha " + DateTime.Now;
            GestorConexiones objconexion = new GestorConexiones();
            await objconexion.ModificarReserva(P_Reserva);
            await objconexion.AgregarReporte(aux);
            return RedirectToAction("Indexa");
        }

    }
}

FEBiblioteca/Controllers/UsuariosController.cs
using FEBiblioteca.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FEBiblioteca.Controllers
{
    public class UsuariosController : Controller
    {

        public async Task<IActionResult> Index()
        {
            GestorConexiones objconexion = new GestorConexiones();
            List<UsuariosModel> lstresultados = await objconexion.ListarUsuarios();
            return View(lstresultados);
        }


        public IActionResult CrearUsuario()
        {
            return View();
        }

   
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Registro()
        {
            return View();
        }

        public IActionResult Menu()
        {
            return View();
        }

        public IActionResult MenuAdministrador()
        {
            return View();
        }
 


        public async Task<IActionResult> InicioSesion(UsuariosModel P_Usuarios)
        {
            ErrorViewModel msj = new ErrorViewModel();
            GestorConexiones objconexion = new GestorConexiones();
            List<UsuariosModel> lstresultados = await objconexion.ConsultarInicioSesion(P_Usuarios);
            lstresultados.FirstOrDefault();
                
            if(lstresultados.Count == 0 )
            {
                msj.RequestId = "Usuario o contrasena no encontrados";
                return RedirectToAction("Login");
            }
            else
            {
                foreach (UsuariosModel usuario in lstresultados)
                {
                    //Arreglar la lista de opciones de cada perfil
                    // crear vista para perfil 2
                    if (usuario.Id_perfil == 2)
                    {
                            return RedirectToAction("Menu");
                    }
                    
                }
                // Crear vista para perfil 1
                return RedirectToAction("MenuAdministrador");
            }
        }

        ///Numero 1 = perfil administrador
        ///Numero 2 =  perfil usuario
        public async Task<IActionResult> Agregar(UsuariosModel P_Usuario)
        {
 
            ErrorViewModel msj = new ErrorViewModel();
            GestorConexiones objconexion = new GestorConexiones();
            List<UsuariosModel> lstresultados = await objconexion.ConsultarUsuarios(new UsuariosModel { Id_Usuario = P_Usuario.Id_Usuario });
            lstresultados.FirstOrDefault();
            if (lstresultados.Count == 0)
            {
                ReportesModel aux = new ReportesModel();
                aux.Reporte = "Se agregó el usuario " + P_Usuario.Id_Usuario + " con fecha " + DateTime.Now;
                await objconexion.Agregar(P_Usuario);
                await objconexion.AgregarReporte(aux);
                return RedirectToAction("Index");
            }
            else
            {
                msj.RequestId = "El usuario tiene una reserva por lo que no se puede eliminar";
                return RedirectToAction("Index");
            }
        }
        public async Task<IActionResult> Registrarse(UsuariosModel P_Usuario)
        {
            ErrorViewModel msj = new ErrorViewModel();
            GestorConexiones objconexion = new GestorConexiones();
            List<UsuariosModel> lstresultados = await objconexion.ConsultarUsuarios(new UsuariosModel { Id_Usuario = P_Usuario.Id_Usuario });
            lstresultados.FirstOrDefault();
            if (lstresultados.Count == 0)
            {
                ReportesModel aux = new ReportesModel();
                aux.Reporte = "Se registró el usuario " + P_Usuario.Id_Usuario + " con fecha " + DateTime.Now;
                P_Usuario.Id_perfil = 2;
                await objconexion.Agregar(P_Usuario);
                await objconexion.AgregarReporte(aux);
                return RedirectToAction("Login");
            }
            else
            {
                msj.RequestId = "El usuario tiene una reserva por lo que no se puede eliminar";
                return RedirectToAction("Registro");
            }
        }
        public async Task<IActionResult> EliminarUsuario(int pUsuario)
        {
            ErrorViewModel msj = new ErrorViewModel();
            GestorConexiones objconexion = new GestorConexiones();
            List<ReservaModel> lstresultados = await objconexion.ConsultarReservaPorIdUsuario(new ReservaModel { Id_usuario = pUsuario });
            lstresultados.FirstOrDefault();
            if (lstresultados.Count == 0)
            {
                ReportesModel aux = new ReportesModel();
                aux.Reporte = "Se eliminó el usuario " + pUsuario + " con fecha " + DateTime.Now;
                await objconexion.EliminarUsuario(new UsuariosModel { Id_Usuario = pUsuario });
                await objconexion.AgregarReporte(aux);
                return RedirectToAction("Index");
            }
            else
            {
                msj.RequestId = "El usuario tiene una reserva por lo que no se puede eliminar";
                return RedirectToAction("Index");
            }
        }


        public async Task<IActionResult> VerInfoModificar(int pUsuario)
        {
            GestorConexiones objconexion = new GestorConexiones();
            List<UsuariosModel> lstresultados = await objconexion.ConsultarUsuarios(new UsuariosModel { Id_Usuario = pUsuario });
            return View(lstresultados.FirstOrDefault());
        }
 

        public async Task<IActionResult> ModificarUsuario(UsuariosModel P_Usuario)
        {
            ReportesModel aux = new ReportesModel();
            aux.Reporte = "Se modificó el usuario " + P_Usuario.Id_Usuario + " con fecha " + DateTime.Now;
            GestorConexiones objconexion = new GestorConexiones();
            await objconexion.ModificarUsuario(P_Usuario);
            await objconexion.AgregarReporte(aux);
            return RedirectToAction("Index");
        }


    }
}

FEBiblioteca/Views/Usuarios/CrearUsuario.cshtml
@model FEBiblioteca.Models.UsuariosModel

@{
    ViewData["Title"] = "CrearUsuario";
}
@section noheader
{
 <h1></H1>
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inicio Hotel</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <style>
        body {
            background-color: #f8f9fa;
            font-family: Arial, sans-serif;
            line-height: 1.6;
        }

        h1 {
            font-family: 'Times New Roman', Times, serif;
            color: #fff;
            font-size: 2.5rem;
            margin-top: 30px;
        }

        hr {
            border: 1px solid #007bff;
            margin: 20px 0;
            color: #fff;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #2c3e50; /* Fondo blanco para el contenido */
            border-radius: 5px; /* Añado bordes redondeados */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Agrego sombra al contenedor */
        }

        label {
            font-family: 'Times New Roman', Times, serif;
            color: #fff;
            font-weight: bold;
            font-size: 1.0rem;
        }

        .form-control {
            border-radius: 5px;
            border: 1px solid #ced4da;
        }

        .btn-primary {
            color: #fff;
            background-color: lightslategrey;
            border-color: #007bff;
        }

            .btn-primary:hover {
                background-color: #0056b3;
                border-color: #0056b3;
            }

        .btn-warning {
            background-color: #ffc107;
            border-color: #ffc107;
        }

            .btn-warning:hover {
                background-color: #e0a800;
                border-color: #e0a800;
            }

        .text-danger {
            color: #dc3545;


        }

        .btn-volver {
            color: #fff;
            background: lightslategrey;
        }
    </style>
</head>
<body>

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h1><img src="https://cdn-icons-png.flaticon.com/512/32/32441.png" alt="Logo" width="50">
                Crear Usuario</h1>
                <hr />

                <form asp-action="Agregar">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Id_Usuario" class="control-label">ID Uusuario</label>
                        <input asp-for="Id_Usuario" class="form-control" />
                        <span asp-validation-for="Id_Usuario" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Nombre" class="control-label"></label>
                        <input asp-for="Nombre" class="form-control" />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Contrasena" class="control-label">Contraseña</label>
                        <input asp-for="Contrasena" class="form-control" maxlength="15" />
                        <span asp-validation-for="Contrasena" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Id_perfil" class="control-label">ID Perfil</label>
                        <input asp-for="Id_perfil" class="form-control" />
                        <span asp-validation-for="Id_perfil" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Guardar" class="btn btn-primary" />
                    </div>
                </form>

                <div class="mt-3 text-center">

                    <a class="btn btn-primary btn-lg" asp-action="Index" asp-controller="Usuarios">Volver al menu</a>
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FEBiblioteca/Views/Usuarios/EliminarUsuarios.cshtml
@model FEBiblioteca.Models.UsuariosModel

@{
    ViewData["Title"] = "EliminarUsuario";
}

<h1>Eliminar Usuario</h1>


<div>
    <h4>Usuarios</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id_Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id_Usuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contrasena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contrasena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id_perfil)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id_perfil)
        </dd>
    </dl>
    
    <form asp-action="EliminarUsuario" asp-controller="Usuario" method="post">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
       <a class="btn btn-warning" asp-action="Index">Volver a Lista</a>
       
    </form>
</div>

FEBiblioteca/Views/Usuarios/Login.cshtml
@model FEBiblioteca.Models.UsuariosModel


@{
    ViewData["Title"] = "Login";
}

<style>
    /* Estilos para el diseño */
    body {
        background-color: #ffffff;
        font-family: Arial, sans-serif;
    }

    h1 {
        text-align: center;
        color: #000;
    }

    #logo {
        float: left;
        margin-right: 20px;
    }

    .login-container {
        width: 300px;
        margin: 100px auto;
        background-color: #203869;
        border: 1px solid #cccccc;
        border-radius: 10px;
        padding: 40px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

        .login-container h2 {
            color: #312F34;
            text-align: center;

        }

    .form-group {
        margin-bottom: 20px;
    }

        .form-group label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
            color: #000000;
        }

        .form-group input[type="text"],
        .form-group input[type="password"] {
            width: 100%;
            padding: 12px;
            border: 1px solid #cccccc;
            border-radius: 5px;
            background-color: #f9f9f9;
        }

        .form-group input[type="submit"] {
            width: 100%;
            padding: 12px;
            background-color: #000000;
            color: #ffffff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

            .form-group input[type="submit"]:hover {
                background-color: #003d71;
            }
</style>

<body >
    <div class="login-container">
        <div id="logo">
            <img src="https://cdn.icon-icons.com/icons2/1381/PNG/512/systemlogout_94057.png" alt="Logo" width="50">
        </div>
        <h2>Log In</h2>
        <form asp-action="InicioSesion" asp-controller="Usuarios">
            <div class="form-group">
                <label asp-for="Id_Usuario" class="control-label">Id de usuario</label>
                <input asp-for="Id_Usuario" class="form-control" required placeholder="Cédula" />
                <span asp-validation-for="Id_Usuario" class="text-danger"></span>

            </div>
            <div class="form-group">
                <label asp-for="Contrasena" class="control-label">Contraseña</label>
                <input asp-for="Contrasena" class="form-control" required type="password" maxlength="15" placeholder="Contraseña" />
                <span asp-validation-for="Contrasena" class="text-danger"></span>

            </div>
            <div class="form-group">
                <input type="submit" value="Ingresar" class="btn btn-primary">

            </div>

        </form>
    </div>
</body>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FEBiblioteca/Views/Usuarios/MenuAdministrador.cshtml
@section noheader
{
    <h1> </h1>
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Home Hotel</title>
    <link href="~/css/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-reboot.css" rel="stylesheet" />

    <style>
        body {
            background-color: #dddddd;
        }
        header {
            background-color: #f9f9f9; /* Fondo gris claro */
            font-family: 'Times New Roman', Times, serif; /* Cambio de tipo de letra a Times New Roman */
            color: #333333; /* Color de texto gris oscuro */
            padding: 10px 0;
        }

        .navbar-brand {
            color: #333333; /* Color del texto del enlace del logo */
            font-weight: bold; /* Texto del logo en negrita */
        }

        .navbar-nav .nav-link {
            color: #333333; /* Color del texto del enlace */
        }

            .navbar-nav .nav-link:hover {
                color: #555555; /* Color del texto del enlace al pasar el ratón */
            }

        .dropdown-menu {
            background-color: #f9f9f9; /* Fondo gris claro para el menú desplegable */
        }

        .dropdown-item {
            color: #333333; /* Color del texto del menú desplegable */
        }

            .dropdown-item:hover {
                background-color: #dddddd; /* Fondo gris más claro al pasar el ratón */
                color: #555555; /* Color del texto al pasar el ratón */
            }
        /*/////////////////////////////////*/
        .container {
            max-width: 800px; /* Ajusta el ancho máximo según tu diseño */
            margin: 0 auto; /* Centra el contenedor horizontalmente */
            font-family: 'Times New Roman', Times, serif; /* Cambia la fuente a Times New Roman */
        }

        h1 {
            font-family: 'Times New Roman', Times, serif; /* Cambia la fuente del título */
            color: #D4AF37; 
            background-color: #dddddd;
        }

        img {
            display: block; /* Asegura que la imagen sea un bloque */
            margin: 0 auto; /* Centra la imagen horizontalmente */
            max-width: 100%; /* Ajusta el ancho máximo de la imagen al contenedor */
        }

    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container">
                <a class="navbar-brand" href="#">Administrador</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="http://localhost:60890/">Cerrar Sesión</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Área Administradora
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-action="Index" asp-controller="Habitaciones">Habitación</a>
                                <a class="dropdown-item" asp-area="" asp-action="Index" asp-controller="Reserva">Reserva</a>
                                <a class="dropdown-item" asp-area="" asp-action="Index" asp-controller="Usuarios">Usuario</a>
                                <a class="dropdown-item" asp-area="" asp-action="Index" asp-controller="Reportes">Reportes</a>
                                <a class="dropdown-item" asp-area="" asp-action="Index" asp-controller="Pagos">Pagos</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <br />
    <br />
    <div class="container mt-4">
        <!-- Contenido de la página -->
        <h1>Bienvenido al área administradora del hotel</h1>
        <img src="~/logo2.jpg" />


    </div>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>